#! /bin/bash
#
# $Author: ee364c10 $ - 
# $Date: 2015-01-13 17:14:17 -0500 (Tue, 13 Jan 2015) $ - 
# $HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S15/students/ee364c10/Lab00/Script3 $ - 
# $Revision: 71537 $ -
Num_Of_Param=$#
Param_Values=$@
for ((I=$@; I > -1; I--))
do
let a=$I%3
if (($a == 0))
then
  echo $I
fi
done

exit 0

 

