# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1429495420);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1429495540);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1431310213);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1431310333);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1429579006);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/ecegrid/a/ee364c10/Lab11");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150326083258");
user_pref("browser.slowStartup.averageTime", 2504);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150326083258");
user_pref("browser.startup.homepage_override.mstone", "31.6.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0,\"bookmarks\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1431310154870");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1431310157109");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1431396557109");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1421651803818");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1421680622942");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1421608572088");
user_pref("datareporting.sessions.current.activeTicks", 46);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1549);
user_pref("datareporting.sessions.current.main", 180);
user_pref("datareporting.sessions.current.sessionRestored", 1641);
user_pref("datareporting.sessions.current.startTime", "1431310091659");
user_pref("datareporting.sessions.current.totalTime", 306);
user_pref("datareporting.sessions.currentIndex", 78);
user_pref("datareporting.sessions.prunedIndex", 77);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 29);
user_pref("extensions.blocklist.pingCountVersion", 13);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.6.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1427876391000,\"rdfTime\":1427374093000}}}]");
user_pref("extensions.lastAppVersion", "31.6.0");
user_pref("extensions.lastPlatformVersion", "31.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20150326083258");
user_pref("gecko.mstone", "31.6.0");
user_pref("idle.lastDailyNotification", 1429498586);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1431310156);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("plugin.soname.list", "libXt.so:libXext.so");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("spellchecker.dictionary", "en-HK");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1427295163);
user_pref("toolkit.startup.last_success", 1431310091);
user_pref("toolkit.telemetry.previousBuildID", "20150326083258");
