# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ecegrid/a/ee364c10/Prelab10/calculator.ui'
#
# Created: Mon Mar 30 21:13:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 347)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.seven = QtGui.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(0, 80, 92, 27))
        self.seven.setObjectName("seven")
        self.eight = QtGui.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(100, 80, 92, 27))
        self.eight.setObjectName("eight")
        self.nine = QtGui.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(200, 80, 92, 27))
        self.nine.setObjectName("nine")
        self.four = QtGui.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(0, 120, 92, 27))
        self.four.setObjectName("four")
        self.five = QtGui.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(100, 120, 92, 27))
        self.five.setObjectName("five")
        self.six = QtGui.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(200, 120, 92, 27))
        self.six.setObjectName("six")
        self.one = QtGui.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(0, 160, 92, 27))
        self.one.setObjectName("one")
        self.two = QtGui.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(100, 160, 92, 27))
        self.two.setObjectName("two")
        self.three = QtGui.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(200, 160, 92, 27))
        self.three.setObjectName("three")
        self.zero = QtGui.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(0, 200, 191, 27))
        self.zero.setObjectName("zero")
        self.dot = QtGui.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(200, 200, 92, 27))
        self.dot.setObjectName("dot")
        self.divide = QtGui.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(300, 80, 92, 27))
        self.divide.setObjectName("divide")
        self.multiply = QtGui.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(300, 120, 92, 27))
        self.multiply.setObjectName("multiply")
        self.minus = QtGui.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(300, 160, 92, 27))
        self.minus.setObjectName("minus")
        self.plus = QtGui.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(300, 200, 92, 27))
        self.plus.setObjectName("plus")
        self.refresh = QtGui.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(410, 80, 92, 71))
        self.refresh.setObjectName("refresh")
        self.equal = QtGui.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(410, 160, 92, 71))
        self.equal.setObjectName("equal")
        self.thousandsSeparator = QtGui.QCheckBox(self.centralwidget)
        self.thousandsSeparator.setGeometry(QtCore.QRect(280, 250, 221, 22))
        self.thousandsSeparator.setObjectName("thousandsSeparator")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 250, 101, 21))
        self.label.setObjectName("label")
        self.textOp = QtGui.QTextEdit(self.centralwidget)
        self.textOp.setGeometry(QtCore.QRect(10, 20, 501, 31))
        self.textOp.setObjectName("textOp")
        self.decimalDigits = QtGui.QComboBox(self.centralwidget)
        self.decimalDigits.setGeometry(QtCore.QRect(120, 246, 85, 31))
        self.decimalDigits.setObjectName("decimalDigits")
        self.decimalDigits.addItem("")
        self.decimalDigits.addItem("")
        self.decimalDigits.addItem("")
        self.decimalDigits.addItem("")
        self.decimalDigits.addItem("")
        self.decimalDigits.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.seven.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.eight.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.nine.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.four.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.five.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.six.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.one.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.two.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.three.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.zero.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.dot.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.divide.setText(QtGui.QApplication.translate("MainWindow", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.multiply.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.minus.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.plus.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("MainWindow", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.equal.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.thousandsSeparator.setText(QtGui.QApplication.translate("MainWindow", "Display Thousands\' Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Decimal Digits", None, QtGui.QApplication.UnicodeUTF8))
        self.textOp.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(0, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.decimalDigits.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))

