# encoding: utf-8
# module selinux._selinux calls itself _selinux
# from /usr/lib64/python2.6/site-packages/selinux/_selinux.so
# by generator 1.136
# no doc

# imports
from _selinux import (SELboolean_name_get, SELboolean_name_set, 
    SELboolean_swigregister, SELboolean_value_get, SELboolean_value_set, 
    SWIG_PyInstanceMethod_New, av_decision_allowed_get, 
    av_decision_allowed_set, av_decision_auditallow_get, 
    av_decision_auditallow_set, av_decision_auditdeny_get, 
    av_decision_auditdeny_set, av_decision_decided_get, 
    av_decision_decided_set, av_decision_flags_get, av_decision_flags_set, 
    av_decision_seqno_get, av_decision_seqno_set, av_decision_swigregister, 
    avc_audit, avc_av_stats, avc_cache_stats_cav_hits_get, 
    avc_cache_stats_cav_hits_set, avc_cache_stats_cav_lookups_get, 
    avc_cache_stats_cav_lookups_set, avc_cache_stats_cav_misses_get, 
    avc_cache_stats_cav_misses_set, avc_cache_stats_cav_probes_get, 
    avc_cache_stats_cav_probes_set, avc_cache_stats_entry_discards_get, 
    avc_cache_stats_entry_discards_set, avc_cache_stats_entry_hits_get, 
    avc_cache_stats_entry_hits_set, avc_cache_stats_entry_lookups_get, 
    avc_cache_stats_entry_lookups_set, avc_cache_stats_entry_misses_get, 
    avc_cache_stats_entry_misses_set, avc_cache_stats_swigregister, 
    avc_cleanup, avc_compute_create, avc_compute_member, avc_context_to_sid, 
    avc_context_to_sid_raw, avc_destroy, avc_entry_ref_ae_get, 
    avc_entry_ref_ae_set, avc_entry_ref_swigregister, avc_get_initial_sid, 
    avc_has_perm, avc_has_perm_noaudit, avc_init, 
    avc_lock_callback_func_alloc_lock_get, 
    avc_lock_callback_func_alloc_lock_set, 
    avc_lock_callback_func_free_lock_get, 
    avc_lock_callback_func_free_lock_set, avc_lock_callback_func_get_lock_get, 
    avc_lock_callback_func_get_lock_set, 
    avc_lock_callback_func_release_lock_get, 
    avc_lock_callback_func_release_lock_set, avc_lock_callback_swigregister, 
    avc_log_callback_func_audit_get, avc_log_callback_func_audit_set, 
    avc_log_callback_func_log_get, avc_log_callback_func_log_set, 
    avc_log_callback_swigregister, avc_memory_callback_func_free_get, 
    avc_memory_callback_func_free_set, avc_memory_callback_func_malloc_get, 
    avc_memory_callback_func_malloc_set, avc_memory_callback_swigregister, 
    avc_netlink_close, avc_netlink_loop, avc_netlink_open, avc_open, 
    avc_reset, avc_sid_stats, avc_sid_to_context, avc_sid_to_context_raw, 
    avc_thread_callback_func_create_thread_get, 
    avc_thread_callback_func_create_thread_set, 
    avc_thread_callback_func_stop_thread_get, 
    avc_thread_callback_func_stop_thread_set, 
    avc_thread_callback_swigregister, checkPasswdAccess, context_free, 
    context_new, context_range_get, context_range_set, context_role_get, 
    context_role_set, context_s_t_ptr_get, context_s_t_ptr_set, 
    context_s_t_swigregister, context_str, context_type_get, context_type_set, 
    context_user_get, context_user_set, delete_SELboolean, delete_av_decision, 
    delete_avc_cache_stats, delete_avc_entry_ref, delete_avc_lock_callback, 
    delete_avc_log_callback, delete_avc_memory_callback, 
    delete_avc_thread_callback, delete_context_s_t, 
    delete_security_class_mapping, delete_security_id, 
    delete_selinux_callback, delete_selinux_opt, fgetfilecon, fgetfilecon_raw, 
    fini_selinuxmnt, fsetfilecon, fsetfilecon_raw, get_default_context, 
    get_default_context_with_level, get_default_context_with_role, 
    get_default_context_with_rolelevel, get_default_type, 
    get_ordered_context_list, get_ordered_context_list_with_level, getcon, 
    getcon_raw, getexeccon, getexeccon_raw, getfilecon, getfilecon_raw, 
    getfscreatecon, getfscreatecon_raw, getkeycreatecon, getkeycreatecon_raw, 
    getpeercon, getpeercon_raw, getpidcon, getpidcon_raw, getprevcon, 
    getprevcon_raw, getseuser, getseuserbyname, getsockcreatecon, 
    getsockcreatecon_raw, is_context_customizable, is_selinux_enabled, 
    is_selinux_mls_enabled, lgetfilecon, lgetfilecon_raw, lsetfilecon, 
    lsetfilecon_raw, manual_user_enter_context, matchmediacon, matchpathcon, 
    matchpathcon_checkmatches, matchpathcon_filespec_add, 
    matchpathcon_filespec_destroy, matchpathcon_filespec_eval, 
    matchpathcon_fini, matchpathcon_index, matchpathcon_init, 
    matchpathcon_init_prefix, new_SELboolean, new_av_decision, 
    new_avc_cache_stats, new_avc_entry_ref, new_avc_lock_callback, 
    new_avc_log_callback, new_avc_memory_callback, new_avc_thread_callback, 
    new_context_s_t, new_security_class_mapping, new_security_id, 
    new_selinux_callback, new_selinux_opt, print_access_vector, 
    query_user_context, rpm_execcon, security_av_perm_to_string, 
    security_av_string, security_canonicalize_context, 
    security_canonicalize_context_raw, security_check_context, 
    security_check_context_raw, security_class_mapping_name_get, 
    security_class_mapping_name_set, security_class_mapping_perms_get, 
    security_class_mapping_perms_set, security_class_mapping_swigregister, 
    security_class_to_string, security_commit_booleans, security_compute_av, 
    security_compute_av_flags, security_compute_av_flags_raw, 
    security_compute_av_raw, security_compute_create, 
    security_compute_create_raw, security_compute_member, 
    security_compute_member_raw, security_compute_relabel, 
    security_compute_relabel_raw, security_compute_user, 
    security_compute_user_raw, security_deny_unknown, security_disable, 
    security_get_boolean_active, security_get_boolean_names, 
    security_get_boolean_pending, security_get_initial_context, 
    security_get_initial_context_raw, security_getenforce, 
    security_id_ctx_get, security_id_ctx_set, security_id_refcnt_get, 
    security_id_refcnt_set, security_id_swigregister, security_load_booleans, 
    security_load_policy, security_policyvers, security_set_boolean, 
    security_set_boolean_list, security_setenforce, selabel_close, 
    selabel_lookup, selabel_lookup_raw, selabel_open, selabel_stats, 
    selinux_binary_policy_path, selinux_booleans_path, 
    selinux_callback_func_audit_get, selinux_callback_func_audit_set, 
    selinux_callback_func_log_get, selinux_callback_func_log_set, 
    selinux_callback_func_policyload_get, 
    selinux_callback_func_policyload_set, 
    selinux_callback_func_setenforce_get, 
    selinux_callback_func_setenforce_set, selinux_callback_func_validate_get, 
    selinux_callback_func_validate_set, selinux_callback_swigregister, 
    selinux_check_passwd_access, selinux_check_securetty_context, 
    selinux_colors_path, selinux_contexts_path, 
    selinux_customizable_types_path, selinux_default_context_path, 
    selinux_default_type_path, selinux_failsafe_context_path, 
    selinux_file_context_cmp, selinux_file_context_homedir_path, 
    selinux_file_context_local_path, selinux_file_context_path, 
    selinux_file_context_subs_path, selinux_file_context_verify, 
    selinux_get_callback, selinux_getenforcemode, selinux_getpolicytype, 
    selinux_homedir_context_path, selinux_init_load_policy, 
    selinux_lsetfilecon_default, selinux_media_context_path, 
    selinux_mkload_policy, selinux_netfilter_context_path, 
    selinux_opt_swigregister, selinux_opt_type_get, selinux_opt_type_set, 
    selinux_opt_value_get, selinux_opt_value_set, selinux_path, 
    selinux_policy_root, selinux_raw_context_to_color, 
    selinux_raw_to_trans_context, selinux_removable_context_path, 
    selinux_reset_config, selinux_securetty_types_path, 
    selinux_sepgsql_context_path, selinux_set_callback, selinux_set_mapping, 
    selinux_trans_to_raw_context, selinux_translations_path, 
    selinux_user_contexts_path, selinux_users_path, selinux_usersconf_path, 
    selinux_virtual_domain_context_path, selinux_virtual_image_context_path, 
    selinux_x_context_path, selinuxfs_exists, set_matchpathcon_flags, 
    set_selinuxmnt, setcon, setcon_raw, setexeccon, setexeccon_raw, 
    setfilecon, setfilecon_raw, setfscreatecon, setfscreatecon_raw, 
    setkeycreatecon, setkeycreatecon_raw, setsockcreatecon, 
    setsockcreatecon_raw, sidget, sidput, string_to_av_perm, 
    string_to_security_class)


# Variables with simple values

APPLETALK_SOCKET__ACCEPT = 8192
APPLETALK_SOCKET__APPEND = 512
APPLETALK_SOCKET__BIND = 1024
APPLETALK_SOCKET__CONNECT = 2048
APPLETALK_SOCKET__CREATE = 8
APPLETALK_SOCKET__GETATTR = 16
APPLETALK_SOCKET__GETOPT = 16384
APPLETALK_SOCKET__IOCTL = 1
APPLETALK_SOCKET__LISTEN = 4096
APPLETALK_SOCKET__LOCK = 64

APPLETALK_SOCKET__NAME_BIND = 2097152

APPLETALK_SOCKET__READ = 2
APPLETALK_SOCKET__RECVFROM = 131072

APPLETALK_SOCKET__RECV_MSG = 524288

APPLETALK_SOCKET__RELABELFROM = 128
APPLETALK_SOCKET__RELABELTO = 256
APPLETALK_SOCKET__SENDTO = 262144

APPLETALK_SOCKET__SEND_MSG = 1048576

APPLETALK_SOCKET__SETATTR = 32
APPLETALK_SOCKET__SETOPT = 32768
APPLETALK_SOCKET__SHUTDOWN = 65536
APPLETALK_SOCKET__WRITE = 4

ASSOCIATION__POLMATCH = 8
ASSOCIATION__RECVFROM = 2
ASSOCIATION__SENDTO = 1
ASSOCIATION__SETCONTEXT = 4

AVC_CACHE_STATS = 1

AVC_CALLBACK_AUDITALLOW_DISABLE = 32
AVC_CALLBACK_AUDITALLOW_ENABLE = 16

AVC_CALLBACK_AUDITDENY_DISABLE = 128
AVC_CALLBACK_AUDITDENY_ENABLE = 64

AVC_CALLBACK_GRANT = 1
AVC_CALLBACK_RESET = 8
AVC_CALLBACK_REVOKE = 4

AVC_CALLBACK_TRY_REVOKE = 2

AVC_OPT_SETENFORCE = 1
AVC_OPT_UNUSED = 0

BLK_FILE__APPEND = 512
BLK_FILE__CREATE = 8
BLK_FILE__EXECUTE = 8192
BLK_FILE__GETATTR = 16
BLK_FILE__IOCTL = 1
BLK_FILE__LINK = 2048
BLK_FILE__LOCK = 64
BLK_FILE__MOUNTON = 65536
BLK_FILE__OPEN = 131072
BLK_FILE__QUOTAON = 32768
BLK_FILE__READ = 2
BLK_FILE__RELABELFROM = 128
BLK_FILE__RELABELTO = 256
BLK_FILE__RENAME = 4096
BLK_FILE__SETATTR = 32
BLK_FILE__SWAPON = 16384
BLK_FILE__UNLINK = 1024
BLK_FILE__WRITE = 4

CAPABILITY2__MAC_ADMIN = 2
CAPABILITY2__MAC_OVERRIDE = 1

CAPABILITY__AUDIT_CONTROL = 1073741824
CAPABILITY__AUDIT_WRITE = 536870912

CAPABILITY__CHOWN = 1

CAPABILITY__DAC_OVERRIDE = 2

CAPABILITY__DAC_READ_SEARCH = 4

CAPABILITY__FOWNER = 8
CAPABILITY__FSETID = 16

CAPABILITY__IPC_LOCK = 16384
CAPABILITY__IPC_OWNER = 32768

CAPABILITY__KILL = 32
CAPABILITY__LEASE = 268435456

CAPABILITY__LINUX_IMMUTABLE = 512

CAPABILITY__MKNOD = 134217728

CAPABILITY__NET_ADMIN = 4096

CAPABILITY__NET_BIND_SERVICE = 1024

CAPABILITY__NET_BROADCAST = 2048
CAPABILITY__NET_RAW = 8192

CAPABILITY__SETFCAP = 2147483648
CAPABILITY__SETGID = 64
CAPABILITY__SETPCAP = 256
CAPABILITY__SETUID = 128

CAPABILITY__SYS_ADMIN = 2097152
CAPABILITY__SYS_BOOT = 4194304
CAPABILITY__SYS_CHROOT = 262144
CAPABILITY__SYS_MODULE = 65536
CAPABILITY__SYS_NICE = 8388608
CAPABILITY__SYS_PACCT = 1048576
CAPABILITY__SYS_PTRACE = 524288
CAPABILITY__SYS_RAWIO = 131072
CAPABILITY__SYS_RESOURCE = 16777216
CAPABILITY__SYS_TIME = 33554432

CAPABILITY__SYS_TTY_CONFIG = 67108864

CHR_FILE__APPEND = 512
CHR_FILE__CREATE = 8
CHR_FILE__ENTRYPOINT = 262144
CHR_FILE__EXECMOD = 524288
CHR_FILE__EXECUTE = 8192

CHR_FILE__EXECUTE_NO_TRANS = 131072

CHR_FILE__GETATTR = 16
CHR_FILE__IOCTL = 1
CHR_FILE__LINK = 2048
CHR_FILE__LOCK = 64
CHR_FILE__MOUNTON = 65536
CHR_FILE__OPEN = 1048576
CHR_FILE__QUOTAON = 32768
CHR_FILE__READ = 2
CHR_FILE__RELABELFROM = 128
CHR_FILE__RELABELTO = 256
CHR_FILE__RENAME = 4096
CHR_FILE__SETATTR = 32
CHR_FILE__SWAPON = 16384
CHR_FILE__UNLINK = 1024
CHR_FILE__WRITE = 4

COMMON_DATABASE__CREATE = 1
COMMON_DATABASE__DROP = 2
COMMON_DATABASE__GETATTR = 4
COMMON_DATABASE__RELABELFROM = 16
COMMON_DATABASE__RELABELTO = 32
COMMON_DATABASE__SETATTR = 8

COMMON_FILE__APPEND = 512
COMMON_FILE__CREATE = 8
COMMON_FILE__EXECUTE = 8192
COMMON_FILE__GETATTR = 16
COMMON_FILE__IOCTL = 1
COMMON_FILE__LINK = 2048
COMMON_FILE__LOCK = 64
COMMON_FILE__MOUNTON = 65536
COMMON_FILE__QUOTAON = 32768
COMMON_FILE__READ = 2
COMMON_FILE__RELABELFROM = 128
COMMON_FILE__RELABELTO = 256
COMMON_FILE__RENAME = 4096
COMMON_FILE__SETATTR = 32
COMMON_FILE__SWAPON = 16384
COMMON_FILE__UNLINK = 1024
COMMON_FILE__WRITE = 4

COMMON_IPC__ASSOCIATE = 64
COMMON_IPC__CREATE = 1
COMMON_IPC__DESTROY = 2
COMMON_IPC__GETATTR = 4
COMMON_IPC__READ = 16
COMMON_IPC__SETATTR = 8

COMMON_IPC__UNIX_READ = 128
COMMON_IPC__UNIX_WRITE = 256

COMMON_IPC__WRITE = 32

COMMON_SOCKET__ACCEPT = 8192
COMMON_SOCKET__APPEND = 512
COMMON_SOCKET__BIND = 1024
COMMON_SOCKET__CONNECT = 2048
COMMON_SOCKET__CREATE = 8
COMMON_SOCKET__GETATTR = 16
COMMON_SOCKET__GETOPT = 16384
COMMON_SOCKET__IOCTL = 1
COMMON_SOCKET__LISTEN = 4096
COMMON_SOCKET__LOCK = 64

COMMON_SOCKET__NAME_BIND = 2097152

COMMON_SOCKET__READ = 2
COMMON_SOCKET__RECVFROM = 131072

COMMON_SOCKET__RECV_MSG = 524288

COMMON_SOCKET__RELABELFROM = 128
COMMON_SOCKET__RELABELTO = 256
COMMON_SOCKET__SENDTO = 262144

COMMON_SOCKET__SEND_MSG = 1048576

COMMON_SOCKET__SETATTR = 32
COMMON_SOCKET__SETOPT = 32768
COMMON_SOCKET__SHUTDOWN = 65536
COMMON_SOCKET__WRITE = 4

CONTEXT__CONTAINS = 2
CONTEXT__TRANSLATE = 1

DBUS__ACQUIRE_SVC = 1

DBUS__SEND_MSG = 2

DB_BLOB__CREATE = 1
DB_BLOB__DROP = 2
DB_BLOB__EXPORT = 512
DB_BLOB__GETATTR = 4
DB_BLOB__IMPORT = 256
DB_BLOB__READ = 64
DB_BLOB__RELABELFROM = 16
DB_BLOB__RELABELTO = 32
DB_BLOB__SETATTR = 8
DB_BLOB__WRITE = 128

DB_COLUMN__CREATE = 1
DB_COLUMN__DROP = 2
DB_COLUMN__GETATTR = 4
DB_COLUMN__INSERT = 512
DB_COLUMN__RELABELFROM = 16
DB_COLUMN__RELABELTO = 32
DB_COLUMN__SELECT = 128
DB_COLUMN__SETATTR = 8
DB_COLUMN__UPDATE = 256
DB_COLUMN__USE = 64

DB_DATABASE__ACCESS = 64
DB_DATABASE__CREATE = 1
DB_DATABASE__DROP = 2
DB_DATABASE__GETATTR = 4

DB_DATABASE__GET_PARAM = 512

DB_DATABASE__INSTALL_MODULE = 128

DB_DATABASE__LOAD_MODULE = 256

DB_DATABASE__RELABELFROM = 16
DB_DATABASE__RELABELTO = 32
DB_DATABASE__SETATTR = 8

DB_DATABASE__SET_PARAM = 1024

DB_PROCEDURE__CREATE = 1
DB_PROCEDURE__DROP = 2
DB_PROCEDURE__ENTRYPOINT = 128
DB_PROCEDURE__EXECUTE = 64
DB_PROCEDURE__GETATTR = 4
DB_PROCEDURE__RELABELFROM = 16
DB_PROCEDURE__RELABELTO = 32
DB_PROCEDURE__SETATTR = 8

DB_TABLE__CREATE = 1
DB_TABLE__DELETE = 1024
DB_TABLE__DROP = 2
DB_TABLE__GETATTR = 4
DB_TABLE__INSERT = 512
DB_TABLE__LOCK = 2048
DB_TABLE__RELABELFROM = 16
DB_TABLE__RELABELTO = 32
DB_TABLE__SELECT = 128
DB_TABLE__SETATTR = 8
DB_TABLE__UPDATE = 256
DB_TABLE__USE = 64

DB_TUPLE__DELETE = 64
DB_TUPLE__INSERT = 32
DB_TUPLE__RELABELFROM = 1
DB_TUPLE__RELABELTO = 2
DB_TUPLE__SELECT = 8
DB_TUPLE__UPDATE = 16
DB_TUPLE__USE = 4

DCCP_SOCKET__ACCEPT = 8192
DCCP_SOCKET__APPEND = 512
DCCP_SOCKET__BIND = 1024
DCCP_SOCKET__CONNECT = 2048
DCCP_SOCKET__CREATE = 8
DCCP_SOCKET__GETATTR = 16
DCCP_SOCKET__GETOPT = 16384
DCCP_SOCKET__IOCTL = 1
DCCP_SOCKET__LISTEN = 4096
DCCP_SOCKET__LOCK = 64

DCCP_SOCKET__NAME_BIND = 2097152
DCCP_SOCKET__NAME_CONNECT = 8388608

DCCP_SOCKET__NODE_BIND = 4194304

DCCP_SOCKET__READ = 2
DCCP_SOCKET__RECVFROM = 131072

DCCP_SOCKET__RECV_MSG = 524288

DCCP_SOCKET__RELABELFROM = 128
DCCP_SOCKET__RELABELTO = 256
DCCP_SOCKET__SENDTO = 262144

DCCP_SOCKET__SEND_MSG = 1048576

DCCP_SOCKET__SETATTR = 32
DCCP_SOCKET__SETOPT = 32768
DCCP_SOCKET__SHUTDOWN = 65536
DCCP_SOCKET__WRITE = 4

DIR__ADD_NAME = 131072

DIR__APPEND = 512
DIR__CREATE = 8
DIR__EXECUTE = 8192
DIR__GETATTR = 16
DIR__IOCTL = 1
DIR__LINK = 2048
DIR__LOCK = 64
DIR__MOUNTON = 65536
DIR__OPEN = 4194304
DIR__QUOTAON = 32768
DIR__READ = 2
DIR__RELABELFROM = 128
DIR__RELABELTO = 256

DIR__REMOVE_NAME = 262144

DIR__RENAME = 4096
DIR__REPARENT = 524288
DIR__RMDIR = 2097152
DIR__SEARCH = 1048576
DIR__SETATTR = 32
DIR__SWAPON = 16384
DIR__UNLINK = 1024
DIR__WRITE = 4

FD__USE = 1

FIFO_FILE__APPEND = 512
FIFO_FILE__CREATE = 8
FIFO_FILE__EXECUTE = 8192
FIFO_FILE__GETATTR = 16
FIFO_FILE__IOCTL = 1
FIFO_FILE__LINK = 2048
FIFO_FILE__LOCK = 64
FIFO_FILE__MOUNTON = 65536
FIFO_FILE__OPEN = 131072
FIFO_FILE__QUOTAON = 32768
FIFO_FILE__READ = 2
FIFO_FILE__RELABELFROM = 128
FIFO_FILE__RELABELTO = 256
FIFO_FILE__RENAME = 4096
FIFO_FILE__SETATTR = 32
FIFO_FILE__SWAPON = 16384
FIFO_FILE__UNLINK = 1024
FIFO_FILE__WRITE = 4

FILESYSTEM__ASSOCIATE = 128
FILESYSTEM__GETATTR = 8
FILESYSTEM__MOUNT = 1
FILESYSTEM__QUOTAGET = 512
FILESYSTEM__QUOTAMOD = 256
FILESYSTEM__RELABELFROM = 16
FILESYSTEM__RELABELTO = 32
FILESYSTEM__REMOUNT = 2
FILESYSTEM__TRANSITION = 64
FILESYSTEM__UNMOUNT = 4

FILE__APPEND = 512
FILE__CREATE = 8
FILE__ENTRYPOINT = 262144
FILE__EXECMOD = 524288
FILE__EXECUTE = 8192

FILE__EXECUTE_NO_TRANS = 131072

FILE__GETATTR = 16
FILE__IOCTL = 1
FILE__LINK = 2048
FILE__LOCK = 64
FILE__MOUNTON = 65536
FILE__OPEN = 1048576
FILE__QUOTAON = 32768
FILE__READ = 2
FILE__RELABELFROM = 128
FILE__RELABELTO = 256
FILE__RENAME = 4096
FILE__SETATTR = 32
FILE__SWAPON = 16384
FILE__UNLINK = 1024
FILE__WRITE = 4

IPC__ASSOCIATE = 64
IPC__CREATE = 1
IPC__DESTROY = 2
IPC__GETATTR = 4
IPC__READ = 16
IPC__SETATTR = 8

IPC__UNIX_READ = 128
IPC__UNIX_WRITE = 256

IPC__WRITE = 32

KEY_SOCKET__ACCEPT = 8192
KEY_SOCKET__APPEND = 512
KEY_SOCKET__BIND = 1024
KEY_SOCKET__CONNECT = 2048
KEY_SOCKET__CREATE = 8
KEY_SOCKET__GETATTR = 16
KEY_SOCKET__GETOPT = 16384
KEY_SOCKET__IOCTL = 1
KEY_SOCKET__LISTEN = 4096
KEY_SOCKET__LOCK = 64

KEY_SOCKET__NAME_BIND = 2097152

KEY_SOCKET__READ = 2
KEY_SOCKET__RECVFROM = 131072

KEY_SOCKET__RECV_MSG = 524288

KEY_SOCKET__RELABELFROM = 128
KEY_SOCKET__RELABELTO = 256
KEY_SOCKET__SENDTO = 262144

KEY_SOCKET__SEND_MSG = 1048576

KEY_SOCKET__SETATTR = 32
KEY_SOCKET__SETOPT = 32768
KEY_SOCKET__SHUTDOWN = 65536
KEY_SOCKET__WRITE = 4

KEY__CREATE = 64
KEY__LINK = 16
KEY__READ = 2
KEY__SEARCH = 8
KEY__SETATTR = 32
KEY__VIEW = 1
KEY__WRITE = 4

LNK_FILE__APPEND = 512
LNK_FILE__CREATE = 8
LNK_FILE__EXECUTE = 8192
LNK_FILE__GETATTR = 16
LNK_FILE__IOCTL = 1
LNK_FILE__LINK = 2048
LNK_FILE__LOCK = 64
LNK_FILE__MOUNTON = 65536
LNK_FILE__QUOTAON = 32768
LNK_FILE__READ = 2
LNK_FILE__RELABELFROM = 128
LNK_FILE__RELABELTO = 256
LNK_FILE__RENAME = 4096
LNK_FILE__SETATTR = 32
LNK_FILE__SWAPON = 16384
LNK_FILE__UNLINK = 1024
LNK_FILE__WRITE = 4

MATCHPATHCON_BASEONLY = 1
MATCHPATHCON_NOTRANS = 2
MATCHPATHCON_VALIDATE = 4

MEMPROTECT__MMAP_ZERO = 1

MSGQ__ASSOCIATE = 64
MSGQ__CREATE = 1
MSGQ__DESTROY = 2
MSGQ__ENQUEUE = 512
MSGQ__GETATTR = 4
MSGQ__READ = 16
MSGQ__SETATTR = 8

MSGQ__UNIX_READ = 128
MSGQ__UNIX_WRITE = 256

MSGQ__WRITE = 32

MSG__RECEIVE = 2
MSG__SEND = 1

NETIF__DCCP_RECV = 64
NETIF__DCCP_SEND = 128

NETIF__EGRESS = 512
NETIF__INGRESS = 256

NETIF__RAWIP_RECV = 16
NETIF__RAWIP_SEND = 32

NETIF__TCP_RECV = 1
NETIF__TCP_SEND = 2

NETIF__UDP_RECV = 4
NETIF__UDP_SEND = 8

NETLINK_AUDIT_SOCKET__ACCEPT = 8192
NETLINK_AUDIT_SOCKET__APPEND = 512
NETLINK_AUDIT_SOCKET__BIND = 1024
NETLINK_AUDIT_SOCKET__CONNECT = 2048
NETLINK_AUDIT_SOCKET__CREATE = 8
NETLINK_AUDIT_SOCKET__GETATTR = 16
NETLINK_AUDIT_SOCKET__GETOPT = 16384
NETLINK_AUDIT_SOCKET__IOCTL = 1
NETLINK_AUDIT_SOCKET__LISTEN = 4096
NETLINK_AUDIT_SOCKET__LOCK = 64

NETLINK_AUDIT_SOCKET__NAME_BIND = 2097152

NETLINK_AUDIT_SOCKET__NLMSG_READ = 4194304
NETLINK_AUDIT_SOCKET__NLMSG_READPRIV = 33554432
NETLINK_AUDIT_SOCKET__NLMSG_RELAY = 16777216

NETLINK_AUDIT_SOCKET__NLMSG_TTY_AUDIT = 67108864

NETLINK_AUDIT_SOCKET__NLMSG_WRITE = 8388608

NETLINK_AUDIT_SOCKET__READ = 2
NETLINK_AUDIT_SOCKET__RECVFROM = 131072

NETLINK_AUDIT_SOCKET__RECV_MSG = 524288

NETLINK_AUDIT_SOCKET__RELABELFROM = 128
NETLINK_AUDIT_SOCKET__RELABELTO = 256
NETLINK_AUDIT_SOCKET__SENDTO = 262144

NETLINK_AUDIT_SOCKET__SEND_MSG = 1048576

NETLINK_AUDIT_SOCKET__SETATTR = 32
NETLINK_AUDIT_SOCKET__SETOPT = 32768
NETLINK_AUDIT_SOCKET__SHUTDOWN = 65536
NETLINK_AUDIT_SOCKET__WRITE = 4

NETLINK_DNRT_SOCKET__ACCEPT = 8192
NETLINK_DNRT_SOCKET__APPEND = 512
NETLINK_DNRT_SOCKET__BIND = 1024
NETLINK_DNRT_SOCKET__CONNECT = 2048
NETLINK_DNRT_SOCKET__CREATE = 8
NETLINK_DNRT_SOCKET__GETATTR = 16
NETLINK_DNRT_SOCKET__GETOPT = 16384
NETLINK_DNRT_SOCKET__IOCTL = 1
NETLINK_DNRT_SOCKET__LISTEN = 4096
NETLINK_DNRT_SOCKET__LOCK = 64

NETLINK_DNRT_SOCKET__NAME_BIND = 2097152

NETLINK_DNRT_SOCKET__READ = 2
NETLINK_DNRT_SOCKET__RECVFROM = 131072

NETLINK_DNRT_SOCKET__RECV_MSG = 524288

NETLINK_DNRT_SOCKET__RELABELFROM = 128
NETLINK_DNRT_SOCKET__RELABELTO = 256
NETLINK_DNRT_SOCKET__SENDTO = 262144

NETLINK_DNRT_SOCKET__SEND_MSG = 1048576

NETLINK_DNRT_SOCKET__SETATTR = 32
NETLINK_DNRT_SOCKET__SETOPT = 32768
NETLINK_DNRT_SOCKET__SHUTDOWN = 65536
NETLINK_DNRT_SOCKET__WRITE = 4

NETLINK_FIREWALL_SOCKET__ACCEPT = 8192
NETLINK_FIREWALL_SOCKET__APPEND = 512
NETLINK_FIREWALL_SOCKET__BIND = 1024
NETLINK_FIREWALL_SOCKET__CONNECT = 2048
NETLINK_FIREWALL_SOCKET__CREATE = 8
NETLINK_FIREWALL_SOCKET__GETATTR = 16
NETLINK_FIREWALL_SOCKET__GETOPT = 16384
NETLINK_FIREWALL_SOCKET__IOCTL = 1
NETLINK_FIREWALL_SOCKET__LISTEN = 4096
NETLINK_FIREWALL_SOCKET__LOCK = 64

NETLINK_FIREWALL_SOCKET__NAME_BIND = 2097152

NETLINK_FIREWALL_SOCKET__NLMSG_READ = 4194304
NETLINK_FIREWALL_SOCKET__NLMSG_WRITE = 8388608

NETLINK_FIREWALL_SOCKET__READ = 2
NETLINK_FIREWALL_SOCKET__RECVFROM = 131072

NETLINK_FIREWALL_SOCKET__RECV_MSG = 524288

NETLINK_FIREWALL_SOCKET__RELABELFROM = 128
NETLINK_FIREWALL_SOCKET__RELABELTO = 256
NETLINK_FIREWALL_SOCKET__SENDTO = 262144

NETLINK_FIREWALL_SOCKET__SEND_MSG = 1048576

NETLINK_FIREWALL_SOCKET__SETATTR = 32
NETLINK_FIREWALL_SOCKET__SETOPT = 32768
NETLINK_FIREWALL_SOCKET__SHUTDOWN = 65536
NETLINK_FIREWALL_SOCKET__WRITE = 4

NETLINK_IP6FW_SOCKET__ACCEPT = 8192
NETLINK_IP6FW_SOCKET__APPEND = 512
NETLINK_IP6FW_SOCKET__BIND = 1024
NETLINK_IP6FW_SOCKET__CONNECT = 2048
NETLINK_IP6FW_SOCKET__CREATE = 8
NETLINK_IP6FW_SOCKET__GETATTR = 16
NETLINK_IP6FW_SOCKET__GETOPT = 16384
NETLINK_IP6FW_SOCKET__IOCTL = 1
NETLINK_IP6FW_SOCKET__LISTEN = 4096
NETLINK_IP6FW_SOCKET__LOCK = 64

NETLINK_IP6FW_SOCKET__NAME_BIND = 2097152

NETLINK_IP6FW_SOCKET__NLMSG_READ = 4194304
NETLINK_IP6FW_SOCKET__NLMSG_WRITE = 8388608

NETLINK_IP6FW_SOCKET__READ = 2
NETLINK_IP6FW_SOCKET__RECVFROM = 131072

NETLINK_IP6FW_SOCKET__RECV_MSG = 524288

NETLINK_IP6FW_SOCKET__RELABELFROM = 128
NETLINK_IP6FW_SOCKET__RELABELTO = 256
NETLINK_IP6FW_SOCKET__SENDTO = 262144

NETLINK_IP6FW_SOCKET__SEND_MSG = 1048576

NETLINK_IP6FW_SOCKET__SETATTR = 32
NETLINK_IP6FW_SOCKET__SETOPT = 32768
NETLINK_IP6FW_SOCKET__SHUTDOWN = 65536
NETLINK_IP6FW_SOCKET__WRITE = 4

NETLINK_KOBJECT_UEVENT_SOCKET__ACCEPT = 8192
NETLINK_KOBJECT_UEVENT_SOCKET__APPEND = 512
NETLINK_KOBJECT_UEVENT_SOCKET__BIND = 1024
NETLINK_KOBJECT_UEVENT_SOCKET__CONNECT = 2048
NETLINK_KOBJECT_UEVENT_SOCKET__CREATE = 8
NETLINK_KOBJECT_UEVENT_SOCKET__GETATTR = 16
NETLINK_KOBJECT_UEVENT_SOCKET__GETOPT = 16384
NETLINK_KOBJECT_UEVENT_SOCKET__IOCTL = 1
NETLINK_KOBJECT_UEVENT_SOCKET__LISTEN = 4096
NETLINK_KOBJECT_UEVENT_SOCKET__LOCK = 64

NETLINK_KOBJECT_UEVENT_SOCKET__NAME_BIND = 2097152

NETLINK_KOBJECT_UEVENT_SOCKET__READ = 2
NETLINK_KOBJECT_UEVENT_SOCKET__RECVFROM = 131072

NETLINK_KOBJECT_UEVENT_SOCKET__RECV_MSG = 524288

NETLINK_KOBJECT_UEVENT_SOCKET__RELABELFROM = 128
NETLINK_KOBJECT_UEVENT_SOCKET__RELABELTO = 256
NETLINK_KOBJECT_UEVENT_SOCKET__SENDTO = 262144

NETLINK_KOBJECT_UEVENT_SOCKET__SEND_MSG = 1048576

NETLINK_KOBJECT_UEVENT_SOCKET__SETATTR = 32
NETLINK_KOBJECT_UEVENT_SOCKET__SETOPT = 32768
NETLINK_KOBJECT_UEVENT_SOCKET__SHUTDOWN = 65536
NETLINK_KOBJECT_UEVENT_SOCKET__WRITE = 4

NETLINK_NFLOG_SOCKET__ACCEPT = 8192
NETLINK_NFLOG_SOCKET__APPEND = 512
NETLINK_NFLOG_SOCKET__BIND = 1024
NETLINK_NFLOG_SOCKET__CONNECT = 2048
NETLINK_NFLOG_SOCKET__CREATE = 8
NETLINK_NFLOG_SOCKET__GETATTR = 16
NETLINK_NFLOG_SOCKET__GETOPT = 16384
NETLINK_NFLOG_SOCKET__IOCTL = 1
NETLINK_NFLOG_SOCKET__LISTEN = 4096
NETLINK_NFLOG_SOCKET__LOCK = 64

NETLINK_NFLOG_SOCKET__NAME_BIND = 2097152

NETLINK_NFLOG_SOCKET__READ = 2
NETLINK_NFLOG_SOCKET__RECVFROM = 131072

NETLINK_NFLOG_SOCKET__RECV_MSG = 524288

NETLINK_NFLOG_SOCKET__RELABELFROM = 128
NETLINK_NFLOG_SOCKET__RELABELTO = 256
NETLINK_NFLOG_SOCKET__SENDTO = 262144

NETLINK_NFLOG_SOCKET__SEND_MSG = 1048576

NETLINK_NFLOG_SOCKET__SETATTR = 32
NETLINK_NFLOG_SOCKET__SETOPT = 32768
NETLINK_NFLOG_SOCKET__SHUTDOWN = 65536
NETLINK_NFLOG_SOCKET__WRITE = 4

NETLINK_ROUTE_SOCKET__ACCEPT = 8192
NETLINK_ROUTE_SOCKET__APPEND = 512
NETLINK_ROUTE_SOCKET__BIND = 1024
NETLINK_ROUTE_SOCKET__CONNECT = 2048
NETLINK_ROUTE_SOCKET__CREATE = 8
NETLINK_ROUTE_SOCKET__GETATTR = 16
NETLINK_ROUTE_SOCKET__GETOPT = 16384
NETLINK_ROUTE_SOCKET__IOCTL = 1
NETLINK_ROUTE_SOCKET__LISTEN = 4096
NETLINK_ROUTE_SOCKET__LOCK = 64

NETLINK_ROUTE_SOCKET__NAME_BIND = 2097152

NETLINK_ROUTE_SOCKET__NLMSG_READ = 4194304
NETLINK_ROUTE_SOCKET__NLMSG_WRITE = 8388608

NETLINK_ROUTE_SOCKET__READ = 2
NETLINK_ROUTE_SOCKET__RECVFROM = 131072

NETLINK_ROUTE_SOCKET__RECV_MSG = 524288

NETLINK_ROUTE_SOCKET__RELABELFROM = 128
NETLINK_ROUTE_SOCKET__RELABELTO = 256
NETLINK_ROUTE_SOCKET__SENDTO = 262144

NETLINK_ROUTE_SOCKET__SEND_MSG = 1048576

NETLINK_ROUTE_SOCKET__SETATTR = 32
NETLINK_ROUTE_SOCKET__SETOPT = 32768
NETLINK_ROUTE_SOCKET__SHUTDOWN = 65536
NETLINK_ROUTE_SOCKET__WRITE = 4

NETLINK_SELINUX_SOCKET__ACCEPT = 8192
NETLINK_SELINUX_SOCKET__APPEND = 512
NETLINK_SELINUX_SOCKET__BIND = 1024
NETLINK_SELINUX_SOCKET__CONNECT = 2048
NETLINK_SELINUX_SOCKET__CREATE = 8
NETLINK_SELINUX_SOCKET__GETATTR = 16
NETLINK_SELINUX_SOCKET__GETOPT = 16384
NETLINK_SELINUX_SOCKET__IOCTL = 1
NETLINK_SELINUX_SOCKET__LISTEN = 4096
NETLINK_SELINUX_SOCKET__LOCK = 64

NETLINK_SELINUX_SOCKET__NAME_BIND = 2097152

NETLINK_SELINUX_SOCKET__READ = 2
NETLINK_SELINUX_SOCKET__RECVFROM = 131072

NETLINK_SELINUX_SOCKET__RECV_MSG = 524288

NETLINK_SELINUX_SOCKET__RELABELFROM = 128
NETLINK_SELINUX_SOCKET__RELABELTO = 256
NETLINK_SELINUX_SOCKET__SENDTO = 262144

NETLINK_SELINUX_SOCKET__SEND_MSG = 1048576

NETLINK_SELINUX_SOCKET__SETATTR = 32
NETLINK_SELINUX_SOCKET__SETOPT = 32768
NETLINK_SELINUX_SOCKET__SHUTDOWN = 65536
NETLINK_SELINUX_SOCKET__WRITE = 4

NETLINK_SOCKET__ACCEPT = 8192
NETLINK_SOCKET__APPEND = 512
NETLINK_SOCKET__BIND = 1024
NETLINK_SOCKET__CONNECT = 2048
NETLINK_SOCKET__CREATE = 8
NETLINK_SOCKET__GETATTR = 16
NETLINK_SOCKET__GETOPT = 16384
NETLINK_SOCKET__IOCTL = 1
NETLINK_SOCKET__LISTEN = 4096
NETLINK_SOCKET__LOCK = 64

NETLINK_SOCKET__NAME_BIND = 2097152

NETLINK_SOCKET__READ = 2
NETLINK_SOCKET__RECVFROM = 131072

NETLINK_SOCKET__RECV_MSG = 524288

NETLINK_SOCKET__RELABELFROM = 128
NETLINK_SOCKET__RELABELTO = 256
NETLINK_SOCKET__SENDTO = 262144

NETLINK_SOCKET__SEND_MSG = 1048576

NETLINK_SOCKET__SETATTR = 32
NETLINK_SOCKET__SETOPT = 32768
NETLINK_SOCKET__SHUTDOWN = 65536
NETLINK_SOCKET__WRITE = 4

NETLINK_TCPDIAG_SOCKET__ACCEPT = 8192
NETLINK_TCPDIAG_SOCKET__APPEND = 512
NETLINK_TCPDIAG_SOCKET__BIND = 1024
NETLINK_TCPDIAG_SOCKET__CONNECT = 2048
NETLINK_TCPDIAG_SOCKET__CREATE = 8
NETLINK_TCPDIAG_SOCKET__GETATTR = 16
NETLINK_TCPDIAG_SOCKET__GETOPT = 16384
NETLINK_TCPDIAG_SOCKET__IOCTL = 1
NETLINK_TCPDIAG_SOCKET__LISTEN = 4096
NETLINK_TCPDIAG_SOCKET__LOCK = 64

NETLINK_TCPDIAG_SOCKET__NAME_BIND = 2097152

NETLINK_TCPDIAG_SOCKET__NLMSG_READ = 4194304
NETLINK_TCPDIAG_SOCKET__NLMSG_WRITE = 8388608

NETLINK_TCPDIAG_SOCKET__READ = 2
NETLINK_TCPDIAG_SOCKET__RECVFROM = 131072

NETLINK_TCPDIAG_SOCKET__RECV_MSG = 524288

NETLINK_TCPDIAG_SOCKET__RELABELFROM = 128
NETLINK_TCPDIAG_SOCKET__RELABELTO = 256
NETLINK_TCPDIAG_SOCKET__SENDTO = 262144

NETLINK_TCPDIAG_SOCKET__SEND_MSG = 1048576

NETLINK_TCPDIAG_SOCKET__SETATTR = 32
NETLINK_TCPDIAG_SOCKET__SETOPT = 32768
NETLINK_TCPDIAG_SOCKET__SHUTDOWN = 65536
NETLINK_TCPDIAG_SOCKET__WRITE = 4

NETLINK_XFRM_SOCKET__ACCEPT = 8192
NETLINK_XFRM_SOCKET__APPEND = 512
NETLINK_XFRM_SOCKET__BIND = 1024
NETLINK_XFRM_SOCKET__CONNECT = 2048
NETLINK_XFRM_SOCKET__CREATE = 8
NETLINK_XFRM_SOCKET__GETATTR = 16
NETLINK_XFRM_SOCKET__GETOPT = 16384
NETLINK_XFRM_SOCKET__IOCTL = 1
NETLINK_XFRM_SOCKET__LISTEN = 4096
NETLINK_XFRM_SOCKET__LOCK = 64

NETLINK_XFRM_SOCKET__NAME_BIND = 2097152

NETLINK_XFRM_SOCKET__NLMSG_READ = 4194304
NETLINK_XFRM_SOCKET__NLMSG_WRITE = 8388608

NETLINK_XFRM_SOCKET__READ = 2
NETLINK_XFRM_SOCKET__RECVFROM = 131072

NETLINK_XFRM_SOCKET__RECV_MSG = 524288

NETLINK_XFRM_SOCKET__RELABELFROM = 128
NETLINK_XFRM_SOCKET__RELABELTO = 256
NETLINK_XFRM_SOCKET__SENDTO = 262144

NETLINK_XFRM_SOCKET__SEND_MSG = 1048576

NETLINK_XFRM_SOCKET__SETATTR = 32
NETLINK_XFRM_SOCKET__SETOPT = 32768
NETLINK_XFRM_SOCKET__SHUTDOWN = 65536
NETLINK_XFRM_SOCKET__WRITE = 4

NODE__DCCP_RECV = 128
NODE__DCCP_SEND = 256

NODE__ENFORCE_DEST = 64

NODE__RAWIP_RECV = 16
NODE__RAWIP_SEND = 32

NODE__RECVFROM = 512
NODE__SENDTO = 1024

NODE__TCP_RECV = 1
NODE__TCP_SEND = 2

NODE__UDP_RECV = 4
NODE__UDP_SEND = 8

NSCD__ADMIN = 16
NSCD__GETGRP = 2
NSCD__GETHOST = 4
NSCD__GETNETGRP = 1024
NSCD__GETPWD = 1
NSCD__GETSERV = 256
NSCD__GETSTAT = 8
NSCD__SHMEMGRP = 64
NSCD__SHMEMHOST = 128
NSCD__SHMEMNETGRP = 2048
NSCD__SHMEMPWD = 32
NSCD__SHMEMSERV = 512

PACKET_SOCKET__ACCEPT = 8192
PACKET_SOCKET__APPEND = 512
PACKET_SOCKET__BIND = 1024
PACKET_SOCKET__CONNECT = 2048
PACKET_SOCKET__CREATE = 8
PACKET_SOCKET__GETATTR = 16
PACKET_SOCKET__GETOPT = 16384
PACKET_SOCKET__IOCTL = 1
PACKET_SOCKET__LISTEN = 4096
PACKET_SOCKET__LOCK = 64

PACKET_SOCKET__NAME_BIND = 2097152

PACKET_SOCKET__READ = 2
PACKET_SOCKET__RECVFROM = 131072

PACKET_SOCKET__RECV_MSG = 524288

PACKET_SOCKET__RELABELFROM = 128
PACKET_SOCKET__RELABELTO = 256
PACKET_SOCKET__SENDTO = 262144

PACKET_SOCKET__SEND_MSG = 1048576

PACKET_SOCKET__SETATTR = 32
PACKET_SOCKET__SETOPT = 32768
PACKET_SOCKET__SHUTDOWN = 65536
PACKET_SOCKET__WRITE = 4

PACKET__FLOW_IN = 8
PACKET__FLOW_OUT = 16

PACKET__FORWARD_IN = 32
PACKET__FORWARD_OUT = 64

PACKET__RECV = 2
PACKET__RELABELTO = 4
PACKET__SEND = 1

PASSWD__CHFN = 2
PASSWD__CHSH = 4
PASSWD__CRONTAB = 16
PASSWD__PASSWD = 1
PASSWD__ROOTOK = 8

PEER__RECV = 1

PROCESS__DYNTRANSITION = 8388608
PROCESS__EXECHEAP = 134217728
PROCESS__EXECMEM = 33554432
PROCESS__EXECSTACK = 67108864
PROCESS__FORK = 1
PROCESS__GETATTR = 65536
PROCESS__GETCAP = 8192
PROCESS__GETPGID = 2048
PROCESS__GETSCHED = 256
PROCESS__GETSESSION = 1024
PROCESS__NOATSECURE = 524288
PROCESS__PTRACE = 128
PROCESS__RLIMITINH = 4194304
PROCESS__SETCAP = 16384
PROCESS__SETCURRENT = 16777216
PROCESS__SETEXEC = 131072
PROCESS__SETFSCREATE = 262144
PROCESS__SETKEYCREATE = 268435456
PROCESS__SETPGID = 4096
PROCESS__SETRLIMIT = 2097152
PROCESS__SETSCHED = 512
PROCESS__SETSOCKCREATE = 536870912
PROCESS__SHARE = 32768
PROCESS__SIGCHLD = 4
PROCESS__SIGINH = 1048576
PROCESS__SIGKILL = 8
PROCESS__SIGNAL = 64
PROCESS__SIGNULL = 32
PROCESS__SIGSTOP = 16
PROCESS__TRANSITION = 2

RAWIP_SOCKET__ACCEPT = 8192
RAWIP_SOCKET__APPEND = 512
RAWIP_SOCKET__BIND = 1024
RAWIP_SOCKET__CONNECT = 2048
RAWIP_SOCKET__CREATE = 8
RAWIP_SOCKET__GETATTR = 16
RAWIP_SOCKET__GETOPT = 16384
RAWIP_SOCKET__IOCTL = 1
RAWIP_SOCKET__LISTEN = 4096
RAWIP_SOCKET__LOCK = 64

RAWIP_SOCKET__NAME_BIND = 2097152

RAWIP_SOCKET__NODE_BIND = 4194304

RAWIP_SOCKET__READ = 2
RAWIP_SOCKET__RECVFROM = 131072

RAWIP_SOCKET__RECV_MSG = 524288

RAWIP_SOCKET__RELABELFROM = 128
RAWIP_SOCKET__RELABELTO = 256
RAWIP_SOCKET__SENDTO = 262144

RAWIP_SOCKET__SEND_MSG = 1048576

RAWIP_SOCKET__SETATTR = 32
RAWIP_SOCKET__SETOPT = 32768
RAWIP_SOCKET__SHUTDOWN = 65536
RAWIP_SOCKET__WRITE = 4

SECCLASS_APPLETALK_SOCKET = 56

SECCLASS_ASSOCIATION = 54

SECCLASS_BLK_FILE = 11

SECCLASS_CAPABILITY = 4
SECCLASS_CAPABILITY2 = 69

SECCLASS_CHR_FILE = 10

SECCLASS_CONTEXT = 59
SECCLASS_DBUS = 52

SECCLASS_DB_BLOB = 67
SECCLASS_DB_COLUMN = 65
SECCLASS_DB_DATABASE = 62
SECCLASS_DB_PROCEDURE = 64
SECCLASS_DB_TABLE = 63
SECCLASS_DB_TUPLE = 66

SECCLASS_DCCP_SOCKET = 60

SECCLASS_DIR = 7
SECCLASS_FD = 8

SECCLASS_FIFO_FILE = 13

SECCLASS_FILE = 6
SECCLASS_FILESYSTEM = 5
SECCLASS_IPC = 29
SECCLASS_KEY = 58

SECCLASS_KEY_SOCKET = 22

SECCLASS_LNK_FILE = 9

SECCLASS_MEMPROTECT = 61
SECCLASS_MSG = 26
SECCLASS_MSGQ = 27
SECCLASS_NETIF = 19

SECCLASS_NETLINK_AUDIT_SOCKET = 49

SECCLASS_NETLINK_DNRT_SOCKET = 51

SECCLASS_NETLINK_FIREWALL_SOCKET = 44

SECCLASS_NETLINK_IP6FW_SOCKET = 50

SECCLASS_NETLINK_KOBJECT_UEVENT_SOCKET = 55

SECCLASS_NETLINK_NFLOG_SOCKET = 46

SECCLASS_NETLINK_ROUTE_SOCKET = 43

SECCLASS_NETLINK_SELINUX_SOCKET = 48

SECCLASS_NETLINK_SOCKET = 20

SECCLASS_NETLINK_TCPDIAG_SOCKET = 45

SECCLASS_NETLINK_XFRM_SOCKET = 47

SECCLASS_NODE = 18
SECCLASS_NSCD = 53
SECCLASS_PACKET = 57

SECCLASS_PACKET_SOCKET = 21

SECCLASS_PASSWD = 30
SECCLASS_PEER = 68
SECCLASS_PROCESS = 2

SECCLASS_RAWIP_SOCKET = 17

SECCLASS_SECURITY = 1
SECCLASS_SEM = 25
SECCLASS_SHM = 28
SECCLASS_SOCKET = 14

SECCLASS_SOCK_FILE = 12

SECCLASS_SYSTEM = 3

SECCLASS_TCP_SOCKET = 15

SECCLASS_UDP_SOCKET = 16

SECCLASS_UNIX_DGRAM_SOCKET = 24

SECCLASS_UNIX_STREAM_SOCKET = 23

SECCLASS_X_APPLICATION_DATA = 73

SECCLASS_X_CLIENT = 39
SECCLASS_X_COLORMAP = 35
SECCLASS_X_CURSOR = 38
SECCLASS_X_DEVICE = 40
SECCLASS_X_DRAWABLE = 31
SECCLASS_X_EVENT = 71
SECCLASS_X_EXTENSION = 42
SECCLASS_X_FONT = 34
SECCLASS_X_GC = 33
SECCLASS_X_PROPERTY = 36
SECCLASS_X_RESOURCE = 70
SECCLASS_X_SCREEN = 32
SECCLASS_X_SELECTION = 37
SECCLASS_X_SERVER = 41

SECCLASS_X_SYNTHETIC_EVENT = 72

SECINITSID_ANY_SOCKET = 8

SECINITSID_DEVNULL = 27
SECINITSID_FILE = 5

SECINITSID_FILE_LABELS = 6

SECINITSID_FS = 4

SECINITSID_ICMP_SOCKET = 14

SECINITSID_IGMP_PACKET = 13

SECINITSID_INIT = 7
SECINITSID_KERNEL = 1
SECINITSID_KMOD = 24
SECINITSID_NETIF = 10
SECINITSID_NETMSG = 11
SECINITSID_NODE = 12
SECINITSID_NUM = 27
SECINITSID_POLICY = 25
SECINITSID_PORT = 9

SECINITSID_SCMP_PACKET = 26

SECINITSID_SECURITY = 2
SECINITSID_SYSCTL = 17

SECINITSID_SYSCTL_DEV = 23
SECINITSID_SYSCTL_FS = 18
SECINITSID_SYSCTL_KERNEL = 19
SECINITSID_SYSCTL_MODPROBE = 16
SECINITSID_SYSCTL_NET = 20

SECINITSID_SYSCTL_NET_UNIX = 21

SECINITSID_SYSCTL_VM = 22

SECINITSID_TCP_SOCKET = 15

SECINITSID_UNLABELED = 3

SECURITY__CHECK_CONTEXT = 8

SECURITY__COMPUTE_AV = 1
SECURITY__COMPUTE_CREATE = 2
SECURITY__COMPUTE_MEMBER = 4
SECURITY__COMPUTE_RELABEL = 32
SECURITY__COMPUTE_USER = 64

SECURITY__LOAD_POLICY = 16

SECURITY__SETBOOL = 256
SECURITY__SETCHECKREQPROT = 1024
SECURITY__SETENFORCE = 128
SECURITY__SETSECPARAM = 512

SELABEL_CTX_DB = 3
SELABEL_CTX_FILE = 0
SELABEL_CTX_MEDIA = 1
SELABEL_CTX_X = 2

SELABEL_DB_BLOB = 8
SELABEL_DB_COLUMN = 4
SELABEL_DB_DATABASE = 1
SELABEL_DB_PROCEDURE = 7
SELABEL_DB_SCHEMA = 2
SELABEL_DB_SEQUENCE = 5
SELABEL_DB_TABLE = 3
SELABEL_DB_TUPLE = 9
SELABEL_DB_VIEW = 6

SELABEL_NOPT = 5

SELABEL_OPT_BASEONLY = 2
SELABEL_OPT_PATH = 3
SELABEL_OPT_SUBSET = 4
SELABEL_OPT_UNUSED = 0
SELABEL_OPT_VALIDATE = 1

SELABEL_X_CLIENT = 3
SELABEL_X_EVENT = 4
SELABEL_X_EXT = 2
SELABEL_X_POLYPROP = 6
SELABEL_X_POLYSELN = 7
SELABEL_X_PROP = 1
SELABEL_X_SELN = 5

SELINUX_AVC = 3

SELINUX_AVD_FLAGS_PERMISSIVE = 1

SELINUX_CB_AUDIT = 1
SELINUX_CB_LOG = 0
SELINUX_CB_POLICYLOAD = 4
SELINUX_CB_SETENFORCE = 3
SELINUX_CB_VALIDATE = 2

SELINUX_DEFAULTUSER = 'user_u'
SELINUX_ERROR = 0
SELINUX_INFO = 2
SELINUX_WARNING = 1

SEM__ASSOCIATE = 64
SEM__CREATE = 1
SEM__DESTROY = 2
SEM__GETATTR = 4
SEM__READ = 16
SEM__SETATTR = 8

SEM__UNIX_READ = 128
SEM__UNIX_WRITE = 256

SEM__WRITE = 32

SHM__ASSOCIATE = 64
SHM__CREATE = 1
SHM__DESTROY = 2
SHM__GETATTR = 4
SHM__LOCK = 512
SHM__READ = 16
SHM__SETATTR = 8

SHM__UNIX_READ = 128
SHM__UNIX_WRITE = 256

SHM__WRITE = 32

SOCKET__ACCEPT = 8192
SOCKET__APPEND = 512
SOCKET__BIND = 1024
SOCKET__CONNECT = 2048
SOCKET__CREATE = 8
SOCKET__GETATTR = 16
SOCKET__GETOPT = 16384
SOCKET__IOCTL = 1
SOCKET__LISTEN = 4096
SOCKET__LOCK = 64

SOCKET__NAME_BIND = 2097152

SOCKET__READ = 2
SOCKET__RECVFROM = 131072

SOCKET__RECV_MSG = 524288

SOCKET__RELABELFROM = 128
SOCKET__RELABELTO = 256
SOCKET__SENDTO = 262144

SOCKET__SEND_MSG = 1048576

SOCKET__SETATTR = 32
SOCKET__SETOPT = 32768
SOCKET__SHUTDOWN = 65536
SOCKET__WRITE = 4

SOCK_FILE__APPEND = 512
SOCK_FILE__CREATE = 8
SOCK_FILE__EXECUTE = 8192
SOCK_FILE__GETATTR = 16
SOCK_FILE__IOCTL = 1
SOCK_FILE__LINK = 2048
SOCK_FILE__LOCK = 64
SOCK_FILE__MOUNTON = 65536
SOCK_FILE__QUOTAON = 32768
SOCK_FILE__READ = 2
SOCK_FILE__RELABELFROM = 128
SOCK_FILE__RELABELTO = 256
SOCK_FILE__RENAME = 4096
SOCK_FILE__SETATTR = 32
SOCK_FILE__SWAPON = 16384
SOCK_FILE__UNLINK = 1024
SOCK_FILE__WRITE = 4

SYSTEM__IPC_INFO = 1

SYSTEM__SYSLOG_CONSOLE = 8
SYSTEM__SYSLOG_MOD = 4
SYSTEM__SYSLOG_READ = 2

TCP_SOCKET__ACCEPT = 8192
TCP_SOCKET__ACCEPTFROM = 16777216
TCP_SOCKET__APPEND = 512
TCP_SOCKET__BIND = 1024
TCP_SOCKET__CONNECT = 2048
TCP_SOCKET__CONNECTTO = 4194304
TCP_SOCKET__CREATE = 8
TCP_SOCKET__GETATTR = 16
TCP_SOCKET__GETOPT = 16384
TCP_SOCKET__IOCTL = 1
TCP_SOCKET__LISTEN = 4096
TCP_SOCKET__LOCK = 64

TCP_SOCKET__NAME_BIND = 2097152
TCP_SOCKET__NAME_CONNECT = 67108864

TCP_SOCKET__NEWCONN = 8388608

TCP_SOCKET__NODE_BIND = 33554432

TCP_SOCKET__READ = 2
TCP_SOCKET__RECVFROM = 131072

TCP_SOCKET__RECV_MSG = 524288

TCP_SOCKET__RELABELFROM = 128
TCP_SOCKET__RELABELTO = 256
TCP_SOCKET__SENDTO = 262144

TCP_SOCKET__SEND_MSG = 1048576

TCP_SOCKET__SETATTR = 32
TCP_SOCKET__SETOPT = 32768
TCP_SOCKET__SHUTDOWN = 65536
TCP_SOCKET__WRITE = 4

UDP_SOCKET__ACCEPT = 8192
UDP_SOCKET__APPEND = 512
UDP_SOCKET__BIND = 1024
UDP_SOCKET__CONNECT = 2048
UDP_SOCKET__CREATE = 8
UDP_SOCKET__GETATTR = 16
UDP_SOCKET__GETOPT = 16384
UDP_SOCKET__IOCTL = 1
UDP_SOCKET__LISTEN = 4096
UDP_SOCKET__LOCK = 64

UDP_SOCKET__NAME_BIND = 2097152

UDP_SOCKET__NODE_BIND = 4194304

UDP_SOCKET__READ = 2
UDP_SOCKET__RECVFROM = 131072

UDP_SOCKET__RECV_MSG = 524288

UDP_SOCKET__RELABELFROM = 128
UDP_SOCKET__RELABELTO = 256
UDP_SOCKET__SENDTO = 262144

UDP_SOCKET__SEND_MSG = 1048576

UDP_SOCKET__SETATTR = 32
UDP_SOCKET__SETOPT = 32768
UDP_SOCKET__SHUTDOWN = 65536
UDP_SOCKET__WRITE = 4

UNIX_DGRAM_SOCKET__ACCEPT = 8192
UNIX_DGRAM_SOCKET__APPEND = 512
UNIX_DGRAM_SOCKET__BIND = 1024
UNIX_DGRAM_SOCKET__CONNECT = 2048
UNIX_DGRAM_SOCKET__CREATE = 8
UNIX_DGRAM_SOCKET__GETATTR = 16
UNIX_DGRAM_SOCKET__GETOPT = 16384
UNIX_DGRAM_SOCKET__IOCTL = 1
UNIX_DGRAM_SOCKET__LISTEN = 4096
UNIX_DGRAM_SOCKET__LOCK = 64

UNIX_DGRAM_SOCKET__NAME_BIND = 2097152

UNIX_DGRAM_SOCKET__READ = 2
UNIX_DGRAM_SOCKET__RECVFROM = 131072

UNIX_DGRAM_SOCKET__RECV_MSG = 524288

UNIX_DGRAM_SOCKET__RELABELFROM = 128
UNIX_DGRAM_SOCKET__RELABELTO = 256
UNIX_DGRAM_SOCKET__SENDTO = 262144

UNIX_DGRAM_SOCKET__SEND_MSG = 1048576

UNIX_DGRAM_SOCKET__SETATTR = 32
UNIX_DGRAM_SOCKET__SETOPT = 32768
UNIX_DGRAM_SOCKET__SHUTDOWN = 65536
UNIX_DGRAM_SOCKET__WRITE = 4

UNIX_STREAM_SOCKET__ACCEPT = 8192
UNIX_STREAM_SOCKET__ACCEPTFROM = 16777216
UNIX_STREAM_SOCKET__APPEND = 512
UNIX_STREAM_SOCKET__BIND = 1024
UNIX_STREAM_SOCKET__CONNECT = 2048
UNIX_STREAM_SOCKET__CONNECTTO = 4194304
UNIX_STREAM_SOCKET__CREATE = 8
UNIX_STREAM_SOCKET__GETATTR = 16
UNIX_STREAM_SOCKET__GETOPT = 16384
UNIX_STREAM_SOCKET__IOCTL = 1
UNIX_STREAM_SOCKET__LISTEN = 4096
UNIX_STREAM_SOCKET__LOCK = 64

UNIX_STREAM_SOCKET__NAME_BIND = 2097152

UNIX_STREAM_SOCKET__NEWCONN = 8388608
UNIX_STREAM_SOCKET__READ = 2
UNIX_STREAM_SOCKET__RECVFROM = 131072

UNIX_STREAM_SOCKET__RECV_MSG = 524288

UNIX_STREAM_SOCKET__RELABELFROM = 128
UNIX_STREAM_SOCKET__RELABELTO = 256
UNIX_STREAM_SOCKET__SENDTO = 262144

UNIX_STREAM_SOCKET__SEND_MSG = 1048576

UNIX_STREAM_SOCKET__SETATTR = 32
UNIX_STREAM_SOCKET__SETOPT = 32768
UNIX_STREAM_SOCKET__SHUTDOWN = 65536
UNIX_STREAM_SOCKET__WRITE = 4

X_APPLICATION_DATA__COPY = 4
X_APPLICATION_DATA__PASTE = 1

X_APPLICATION_DATA__PASTE_AFTER_CONFIRM = 2

X_CLIENT__DESTROY = 1
X_CLIENT__GETATTR = 2
X_CLIENT__MANAGE = 8
X_CLIENT__SETATTR = 4

X_COLORMAP__ADD_COLOR = 32

X_COLORMAP__CREATE = 1
X_COLORMAP__DESTROY = 2
X_COLORMAP__GETATTR = 16
X_COLORMAP__INSTALL = 128
X_COLORMAP__READ = 4

X_COLORMAP__REMOVE_COLOR = 64

X_COLORMAP__UNINSTALL = 256
X_COLORMAP__USE = 512
X_COLORMAP__WRITE = 8

X_CURSOR__CREATE = 1
X_CURSOR__DESTROY = 2
X_CURSOR__GETATTR = 16
X_CURSOR__READ = 4
X_CURSOR__SETATTR = 32
X_CURSOR__USE = 64
X_CURSOR__WRITE = 8

X_DEVICE__BELL = 128

X_DEVICE__FORCE_CURSOR = 256

X_DEVICE__FREEZE = 512
X_DEVICE__GETATTR = 1
X_DEVICE__GETFOCUS = 32
X_DEVICE__GRAB = 1024
X_DEVICE__MANAGE = 2048
X_DEVICE__READ = 8
X_DEVICE__SETATTR = 2
X_DEVICE__SETFOCUS = 64
X_DEVICE__USE = 4
X_DEVICE__WRITE = 16

X_DRAWABLE__ADD_CHILD = 256

X_DRAWABLE__BLEND = 16
X_DRAWABLE__CREATE = 1
X_DRAWABLE__DESTROY = 2
X_DRAWABLE__GETATTR = 32

X_DRAWABLE__GET_PROPERTY = 2048

X_DRAWABLE__HIDE = 65536

X_DRAWABLE__LIST_CHILD = 128
X_DRAWABLE__LIST_PROPERTY = 1024

X_DRAWABLE__MANAGE = 8192
X_DRAWABLE__OVERRIDE = 16384
X_DRAWABLE__READ = 4
X_DRAWABLE__RECEIVE = 262144

X_DRAWABLE__REMOVE_CHILD = 512

X_DRAWABLE__SEND = 131072
X_DRAWABLE__SETATTR = 64

X_DRAWABLE__SET_PROPERTY = 4096

X_DRAWABLE__SHOW = 32768
X_DRAWABLE__WRITE = 8

X_EVENT__RECEIVE = 2
X_EVENT__SEND = 1

X_EXTENSION__QUERY = 1
X_EXTENSION__USE = 2

X_FONT__ADD_GLYPH = 8

X_FONT__CREATE = 1
X_FONT__DESTROY = 2
X_FONT__GETATTR = 4

X_FONT__REMOVE_GLYPH = 16

X_FONT__USE = 32

X_GC__CREATE = 1
X_GC__DESTROY = 2
X_GC__GETATTR = 4
X_GC__SETATTR = 8
X_GC__USE = 16

X_PROPERTY__APPEND = 16
X_PROPERTY__CREATE = 1
X_PROPERTY__DESTROY = 2
X_PROPERTY__GETATTR = 32
X_PROPERTY__READ = 4
X_PROPERTY__SETATTR = 64
X_PROPERTY__WRITE = 8

X_RESOURCE__READ = 1
X_RESOURCE__WRITE = 2

X_SCREEN__GETATTR = 1

X_SCREEN__HIDE_CURSOR = 4

X_SCREEN__SAVER_GETATTR = 16
X_SCREEN__SAVER_HIDE = 64
X_SCREEN__SAVER_SETATTR = 32
X_SCREEN__SAVER_SHOW = 128

X_SCREEN__SETATTR = 2

X_SCREEN__SHOW_CURSOR = 8

X_SELECTION__GETATTR = 4
X_SELECTION__READ = 1
X_SELECTION__SETATTR = 8
X_SELECTION__WRITE = 2

X_SERVER__DEBUG = 8
X_SERVER__GETATTR = 1
X_SERVER__GRAB = 16
X_SERVER__MANAGE = 32
X_SERVER__RECORD = 4
X_SERVER__SETATTR = 2

X_SYNTHETIC_EVENT__RECEIVE = 2
X_SYNTHETIC_EVENT__SEND = 1

# no functions
# no classes
