onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/CLK
add wave -noupdate /system_tb/nRST
add wave -noupdate /system_tb/DUT/CPU/ccif/iwait
add wave -noupdate /system_tb/DUT/CPU/ccif/dwait
add wave -noupdate /system_tb/DUT/CPU/ccif/iREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/iload
add wave -noupdate /system_tb/DUT/CPU/ccif/dload
add wave -noupdate -expand /system_tb/DUT/CPU/ccif/dstore
add wave -noupdate /system_tb/DUT/CPU/ccif/iaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramREN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstate
add wave -noupdate /system_tb/DUT/CPU/ccif/ramaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstore
add wave -noupdate /system_tb/DUT/CPU/ccif/ramload
add wave -noupdate /system_tb/DUT/CPU/DP/PC_INIT
add wave -noupdate /system_tb/DUT/CPU/DP/CLK
add wave -noupdate /system_tb/DUT/CPU/DP/nRST
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_EX
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_M
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_WB
add wave -noupdate /system_tb/DUT/CPU/DP/jal_EX
add wave -noupdate /system_tb/DUT/CPU/DP/jal_M
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/beq
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/bne
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegDst
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemToReg
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ExtOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ShiftOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/lui
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dR_REQ
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dW_REQ
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/ex_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/ex_regRs
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/mem_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/wb_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/mem_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/wb_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/ForwardA
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/ForwardB
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/isLUI_EX
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/stCntl
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/op_M
add wave -noupdate /system_tb/DUT/CPU/DP/FORWARDING_UNIT/fuif/op_WB
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/portA
add wave -noupdate -radix hexadecimal /system_tb/DUT/CPU/DP/ALU/alpts/portB
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/aluOP
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/portO
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/nFlag
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/oFlag
add wave -noupdate /system_tb/DUT/CPU/DP/ALU/alpts/zFlag
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfif/rdat2
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate -radix hexadecimal /system_tb/DUT/CPU/DP/instruction
add wave -noupdate /system_tb/DUT/CPU/DP/instruction_D
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/j
add wave -noupdate /system_tb/DUT/CPU/DP/j_EX
add wave -noupdate /system_tb/DUT/CPU/DP/j_M
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jal
add wave -noupdate /system_tb/DUT/CPU/DP/jal_EX
add wave -noupdate /system_tb/DUT/CPU/DP/jal_M
add wave -noupdate /system_tb/DUT/CPU/DP/jal_WB
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jr
add wave -noupdate /system_tb/DUT/CPU/DP/jr_EX
add wave -noupdate /system_tb/DUT/CPU/DP/jr_M
add wave -noupdate /system_tb/DUT/CPU/DP/jal_or_j
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_de
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_EX
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_M
add wave -noupdate /system_tb/DUT/CPU/DP/PROGRAM_COUNTER/pc_EN
add wave -noupdate /system_tb/DUT/CPU/DP/npc
add wave -noupdate /system_tb/DUT/CPU/DP/pc
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_4
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_4_D
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_4_EX
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_4_M
add wave -noupdate /system_tb/DUT/CPU/DP/pc_next
add wave -noupdate /system_tb/DUT/CPU/DP/REGISTER_FILE/rfile
add wave -noupdate /system_tb/DUT/CPU/DP/lui_EX
add wave -noupdate /system_tb/DUT/CPU/DP/lui_M
add wave -noupdate /system_tb/DUT/CPU/DP/halt_M
add wave -noupdate /system_tb/DUT/CPU/DP/halt_EX
add wave -noupdate /system_tb/DUT/CPU/DP/j_EX
add wave -noupdate /system_tb/DUT/CPU/DP/jr_EX
add wave -noupdate /system_tb/DUT/CPU/DP/ShiftOp_EX
add wave -noupdate /system_tb/DUT/CPU/DP/ALUSrc_EX
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_EX
add wave -noupdate /system_tb/DUT/CPU/DP/ExtOp_EX
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/negative
add wave -noupdate /system_tb/DUT/CPU/DP/overflow
add wave -noupdate /system_tb/DUT/CPU/DP/pipe_en
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_output_1
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_output_2
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_JAL_output_1
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_JAL_output
add wave -noupdate /system_tb/DUT/CPU/DP/shamt_EX
add wave -noupdate /system_tb/DUT/CPU/DP/dummyRt
add wave -noupdate /system_tb/DUT/CPU/DP/dummyRt_DE
add wave -noupdate /system_tb/DUT/CPU/DP/rt_EX
add wave -noupdate /system_tb/DUT/CPU/DP/dummyRs
add wave -noupdate /system_tb/DUT/CPU/DP/dummyRs_DE
add wave -noupdate /system_tb/DUT/CPU/DP/rd_EX
add wave -noupdate /system_tb/DUT/CPU/DP/rb_content_M
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_JAL_output_M
add wave -noupdate /system_tb/DUT/CPU/DP/ALUSrc_output
add wave -noupdate /system_tb/DUT/CPU/DP/extended_imm16
add wave -noupdate /system_tb/DUT/CPU/DP/extended_shamt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/ihit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dhit
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/imemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemREN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemWEN
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/flushed
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_M
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_de
add wave -noupdate /system_tb/DUT/CPU/DP/flushed_EX
add wave -noupdate -radix hexadecimal /system_tb/DUT/CPU/DP/instruction_EX
add wave -noupdate /system_tb/DUT/CPU/DP/instruction_M
add wave -noupdate /system_tb/DUT/CPU/DP/d_instr_DE
add wave -noupdate /system_tb/DUT/CPU/DP/d_instr_EX
add wave -noupdate /system_tb/DUT/CPU/DP/d_instr_M
add wave -noupdate /system_tb/DUT/CPU/DP/pc
add wave -noupdate /system_tb/DUT/CPU/DP/stall_LDST
add wave -noupdate /system_tb/DUT/CPU/DP/noop_EX
add wave -noupdate /system_tb/DUT/CPU/DP/stall_LDST
add wave -noupdate /system_tb/DUT/CPU/DP/pipe_en
add wave -noupdate /system_tb/DUT/CPU/DP/pipe_en_others
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemstore
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dR_REQ
add wave -noupdate /system_tb/DUT/CPU/DP/dR_REQ_EX
add wave -noupdate /system_tb/DUT/CPU/DP/dR_REQ_M
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/dW_REQ
add wave -noupdate /system_tb/DUT/CPU/DP/dW_REQ_EX
add wave -noupdate /system_tb/DUT/CPU/DP/dW_REQ_M
add wave -noupdate /system_tb/DUT/CPU/DP/dmemload_WB
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramaddr
add wave -noupdate /system_tb/DUT/CPU/DP/porto_M
add wave -noupdate /system_tb/DUT/CPU/ccif/daddr
add wave -noupdate /system_tb/DUT/CPU/DP/porto_WB
add wave -noupdate /system_tb/DUT/CPU/DP/RegDst_JAL_output_WB
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/RegWrite_EX
add wave -noupdate /system_tb/DUT/CPU/DP/RegWrite_M
add wave -noupdate /system_tb/DUT/CPU/DP/RegWrite_WB
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/MemToReg
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_EX
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_M
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_WB
add wave -noupdate /system_tb/DUT/CPU/DP/MemToReg_output
add wave -noupdate /system_tb/DUT/CPU/DP/lui_WB
add wave -noupdate /system_tb/DUT/CPU/DP/jal_WB
add wave -noupdate /system_tb/DUT/CPU/DP/dmemload_WB
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_4_WB
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/portO
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wsel
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/wdat
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/WEN
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rsel2
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat1
add wave -noupdate /system_tb/DUT/CPU/DP/rfif/rdat2
add wave -noupdate /system_tb/DUT/CPU/DP/ALUOp_EX
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/portA
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/portB
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/aluOP
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/portO
add wave -noupdate /system_tb/DUT/CPU/DP/lui_M
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/nFlag
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/oFlag
add wave -noupdate /system_tb/DUT/CPU/DP/aluif/zFlag
add wave -noupdate /system_tb/DUT/CPU/DP/zero
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ForwardA
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ForwardB
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/stCntl
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/isLUI_EX
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/ra_content_EX
add wave -noupdate /system_tb/DUT/CPU/DP/rb_content_EX
add wave -noupdate /system_tb/DUT/CPU/DP/shifted_ALUSrc_output
add wave -noupdate /system_tb/DUT/CPU/DP/portA_M
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/imemload
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/j
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jr
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/jal
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/beq
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/bne
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/halt
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/RegDst
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUSrc
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ALUOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ExtOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/ShiftOp
add wave -noupdate /system_tb/DUT/CPU/DP/cuif/lui
add wave -noupdate /system_tb/DUT/CPU/DP/Dummy_rs_EX
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ex_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ex_regRs
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/mem_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/wb_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/mem_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/wb_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/dpif/dmemload
add wave -noupdate /system_tb/DUT/CPU/ccif/iwait
add wave -noupdate /system_tb/DUT/CPU/ccif/dwait
add wave -noupdate /system_tb/DUT/CPU/ccif/iREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dREN
add wave -noupdate /system_tb/DUT/CPU/ccif/dWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/iload
add wave -noupdate /system_tb/DUT/CPU/DP/extended_imm16
add wave -noupdate /system_tb/DUT/CPU/ccif/dload
add wave -noupdate /system_tb/DUT/CPU/ccif/dstore
add wave -noupdate /system_tb/DUT/CPU/ccif/iaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/daddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramWEN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramREN
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstate
add wave -noupdate /system_tb/DUT/CPU/ccif/ramaddr
add wave -noupdate /system_tb/DUT/CPU/ccif/ramstore
add wave -noupdate /system_tb/DUT/CPU/ccif/ramload
add wave -noupdate /system_tb/DUT/CPU/DP/hduif/stall
add wave -noupdate /system_tb/DUT/CPU/DP/hduif/ex_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/hduif/de_regRs
add wave -noupdate /system_tb/DUT/CPU/DP/hduif/de_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/hduif/ex_dR_REQ
add wave -noupdate /system_tb/DUT/CPU/DP/branch_add
add wave -noupdate /system_tb/DUT/CPU/DP/pc_plus_M
add wave -noupdate /system_tb/DUT/CPU/DP/jump_address
add wave -noupdate /system_tb/DUT/CPU/DP/branch_mux_control
add wave -noupdate /system_tb/DUT/CPU/DP/portO_EX
add wave -noupdate /system_tb/DUT/CPU/DP/porto_M
add wave -noupdate /system_tb/DUT/CPU/DP/jump_address
add wave -noupdate /system_tb/DUT/CPU/DP/jump_address
add wave -noupdate /system_tb/DUT/CPU/DP/intermediate_jump_op
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_sign_extended_1
add wave -noupdate /system_tb/DUT/CPU/DP/imm16_sign_extended
add wave -noupdate /system_tb/DUT/CPU/DP/branch_add
add wave -noupdate /system_tb/DUT/CPU/DP/branch_mux_output
add wave -noupdate /system_tb/DUT/CPU/DP/branch_mux_control
add wave -noupdate /system_tb/DUT/CPU/DP/jal_or_j
add wave -noupdate /system_tb/DUT/CPU/DP/intermediate_jump_mux
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/de_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ex_regRt
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ex_regRs
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/mem_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/wb_regRd
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/mem_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/wb_RegWrite
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/dWEN
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/dREN
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ForwardA
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/ForwardB
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/isLUI_EX
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/isIType
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/stCntl2
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/stCntl
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/op_M
add wave -noupdate /system_tb/DUT/CPU/DP/fuif/op_WB
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {38000000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 223
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 10
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {37525572 ps} {38474428 ps}
