default:
	cd makeprocs; make
	cd hello_world; make
	cd step1; make
	cd step2; make
	cd step3; make
	cd step4; make
	cd step6; make


clean:
	cd makeprocs; make clean
	cd hello_world; make clean
	cd step1; make clean
	cd step2; make clean
	cd step3; make clean
	cd step4; make clean
	cd step6; make clean


run:
	cd ../../bin; dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 7; ee469_fixterminal

